import os
import cv2
import pandas as pd
import numpy as np
import torch
import shutil
import torch
import torch.nn as nn
import math
from torch.utils.model_zoo import load_url as load_state_dict_from_url
from torch.backends import cudnn

import os, argparse, random

#import BGRemove_GrabCut
#import BGRemove_DL
import PartAttGen
#from visualize import visualize
import model


if __name__ == '__main__':
    torch.manual_seed(1234)
    torch.cuda.manual_seed(1234)
    torch.cuda.manual_seed_all(1234)
    np.random.seed(1234)
    random.seed(1234)
    torch.backends.cudnn.deterministic = True
    cudnn.benchmark = True
    #os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    parser = argparse.ArgumentParser(description='Train Semantics-guided Part Attention Network (SPAN)', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    #parser.add_argument('--mode', required=True, help='Select training or implementation mode; option: ["train", "implement"]')
    parser.add_argument('--image_root', required=True, help='path to ReId dataset')
    #parser.add_argument('--mask_grabcut_root', default='./BGRemove_GrabCut', help='path to foreground mask generated by GrabCut')
    #parser.add_argument('--mask_dl_root', default='./BGRemove_DL', help='path to foreground mask generated by deep learning network')
    parser.add_argument('--mask_dl_ckpt', default='./BGRemove_DL_ckpt', help='path to store foreground mask generator checkpoint')
    #parser.add_argument('--dataset_csv', default='./dataset.csv', help='Dataset csv file used for training part attention mask generator')
    #parser.add_argument('--part_att_root', default='./PartAttMask', help='path to generated part attention mask')
    parser.add_argument('--part_att_ckpt', default='./PartAttMask_ckpt', help='path to store part attention mask generator checkpoint')
    args = parser.parse_args()

    Folder_list=os.listdir(args.image_root)
    for k in Folder_list:
        
        for (root,dirs,files) in os.walk(args.image_root+'/'+k, topdown=True):
            if len(dirs) == 0:
                for i in files:
                    shutil.copy(root+'/'+i, args.image_root+'/'+k+'/'+i)
                print(root)
                shutil.rmtree(root)

        part_att_root = args.image_root+'/mask_generate_{}/part_attention'.format(k)


        print("\n### Generate part attention mask ###")
        checkpoint = os.path.join(args.part_att_ckpt, '10.ckpt')
        PartAttGen.implement(image_root=args.image_root,
                            mask_root= part_att_root,
                            model= model.PartAtt_Generator().to(device),
                            device= device,
                            checkpoint= checkpoint)


        for (root,dirs,files) in os.walk(args.image_root+'/mask_generate_'+k+'/part_attention', topdown=True):
            if len(dirs)==0:
                for i in files:
                    shutil.copy(root+'/'+i, args.image_root+'/mask_generate_'+k+'/part_attention'+'/'+i)
                shutil.rmtree(root)

        


    
        
